import { Role, Event } from "../classes/enums";
import { normalizeChampionName } from "../utils/championUtils";

export interface ChampionData {
    name: string,
    roles: Role[]
}

export const CHAMPIONS: { [key: string]: Role[] } = {
    Aatrox: [Role.TOP],
    Ahri: [Role.MID],
    Akali: [Role.MID, Role.TOP],
    Akshan: [Role.MID, Role.ADC],
    Alistar: [Role.SUP],
    Amumu: [Role.JNG, Role.SUP],
    Anivia: [Role.MID, Role.ADC],
    Annie: [Role.MID],
    Aphelios: [Role.ADC],
    Ashe: [Role.ADC, Role.SUP],
    'Aurelion Sol': [Role.MID],
    Azir: [Role.MID],
    Bard: [Role.SUP],
    Blitzcrank: [Role.SUP],
    Brand: [Role.MID, Role.SUP],
    Braum: [Role.SUP],
    Caitlyn: [Role.ADC],
    Camille: [Role.TOP],
    Cassiopeia: [Role.MID, Role.ADC, Role.TOP],
    'Cho\'Gath': [Role.TOP, Role.JNG],
    Corki: [Role.MID],
    Darius: [Role.TOP, Role.JNG],
    Diana: [Role.MID, Role.JNG],
    Mundo: [Role.TOP, Role.JNG],
    Draven: [Role.ADC],
    Ekko: [Role.MID, Role.JNG],
    Elise: [Role.JNG],
    Evelynn: [Role.JNG],
    Ezreal: [Role.MID, Role.ADC],
    Fiddlesticks: [Role.JNG],
    Fiora: [Role.TOP],
    Fizz: [Role.MID],
    Galio: [Role.MID, Role.SUP],
    Gangplank: [Role.TOP],
    Garen: [Role.TOP, Role.MID, Role.JNG],
    Gnar: [Role.TOP],
    Gragas: [Role.TOP],
    Graves: [Role.JNG, Role.MID],
    Gwen: [Role.TOP, Role.JNG],
    Hecarim: [Role.JNG],
    Heimerdinger: [Role.MID],
    Illaoi: [Role.TOP],
    Irelia: [Role.TOP, Role.MID, Role.ADC],
    Ivern: [Role.JNG],
    Janna: [Role.SUP],
    'Jarvan IV': [Role.JNG],
    Jax: [Role.TOP, Role.JNG],
    Jayce: [Role.TOP, Role.MID],
    Jhin: [Role.ADC],
    Jinx: [Role.ADC],
    'Kai\'sa': [Role.ADC],
    Kalista: [Role.ADC],
    Karma: [Role.TOP, Role.SUP],
    Karthus: [Role.JNG],
    Kassadin: [Role.MID],
    Katarina: [Role.MID],
    Kayle: [Role.TOP],
    Kayn: [Role.JNG],
    Kennen: [Role.TOP],
    'Kha\'Zix': [Role.JNG],
    Kindred: [Role.JNG],
    Kled: [Role.TOP],
    'Kog\'Maw': [Role.ADC],
    LeBlanc: [Role.MID],
    'Lee Sin': [Role.JNG],
    Leona: [Role.SUP],
    Lillia: [Role.JNG, Role.TOP],
    Lissandra: [Role.MID],
    Lucian: [Role.ADC, Role.MID, Role.TOP],
    Lulu: [Role.SUP],
    Lux: [Role.MID, Role.SUP],
    Malphite: [Role.TOP, Role.MID, Role.JNG, Role.SUP],
    Malzahar: [Role.MID],
    Maoki: [Role.TOP, Role.SUP],
    'Master Yi': [Role.JNG],
    'Miss Fortune': [Role.ADC, Role.SUP],
    Mordekaiser: [Role.TOP, Role.JNG],
    Morgana: [Role.MID, Role.JNG, Role.SUP],
    Nami: [Role.SUP],
    Nasus: [Role.TOP, Role.JNG],
    Nautilus: [Role.SUP],
    Neeko: [Role.MID, Role.TOP],
    Nidalee: [Role.JNG],
    Nocturne: [Role.JNG, Role.MID],
    Nunu: [Role.JNG],
    Olaf: [Role.JNG],
    Orianna: [Role.MID],
    Ornn: [Role.TOP],
    Pantheon: [Role.TOP, Role.MID, Role.JNG, Role.SUP],
    Poppy: [Role.TOP, Role.JNG],
    Pyke: [Role.MID, Role.SUP],
    Qiyana: [Role.MID, Role.JNG],
    Quinn: [Role.TOP],
    Rakan: [Role.SUP],
    Rammus: [Role.JNG],
    'Rek\'Sai': [Role.JNG],
    Rell: [Role.SUP],
    Renekton: [Role.TOP],
    Rengar: [Role.TOP, Role.JNG],
    Riven: [Role.TOP],
    Rumble: [Role.TOP],
    Ryze: [Role.TOP, Role.MID],
    Samira: [Role.ADC],
    Sejuani: [Role.JNG],
    Senna: [Role.ADC, Role.SUP],
    Seraphine: [Role.MID, Role.ADC, Role.SUP],
    Sett: [Role.TOP, Role.SUP],
    Shaco: [Role.JNG],
    Shen: [Role.TOP],
    Shyvana: [Role.JNG],
    Singed: [Role.TOP],
    Sion: [Role.TOP, Role.JNG],
    Sivir: [Role.ADC],
    Skarner: [Role.JNG],
    Sona: [Role.SUP],
    Soraka: [Role.SUP],
    Swain: [Role.ADC, Role.SUP],
    Sylas: [Role.TOP, Role.MID, Role.JNG],
    Syndra: [Role.MID],
    'Tahm Kench': [Role.TOP, Role.SUP],
    Taliyah: [Role.MID, Role.JNG],
    Talon: [Role.MID, Role.JNG],
    Taric: [Role.SUP],
    Teemo: [Role.TOP, Role.SUP],
    Thresh: [Role.SUP],
    Tristana: [Role.MID, Role.ADC],
    Trundle: [Role.TOP, Role.JNG],
    Tryndamere: [Role.TOP],
    'Twisted Fate': [Role.MID],
    Twitch: [Role.ADC],
    Udyr: [Role.JNG],
    Urgot: [Role.TOP],
    Varus: [Role.ADC],
    Vayne: [Role.TOP, Role.ADC],
    Veigar: [Role.MID],
    'Vel\'Koz': [Role.MID, Role.SUP],
    Vex: [Role.MID],
    Vi: [Role.JNG, Role.MID],
    Viego: [Role.TOP, Role.MID, Role.JNG],
    Viktor: [Role.MID],
    Vladimir: [Role.MID, Role.TOP],
    Volibear: [Role.TOP, Role.JNG],
    Warwick: [Role.JNG],
    Wukong: [Role.TOP, Role.JNG],
    Xayah: [Role.ADC],
    Xerath: [Role.MID, Role.SUP],
    'Xin Zhao': [Role.JNG],
    Yasuo: [Role.TOP, Role.MID, Role.ADC],
    Yone: [Role.TOP, Role.MID],
    Yorick: [Role.TOP],
    Yuumi: [Role.SUP],
    Zac: [Role.JNG],
    Zed: [Role.MID, Role.JNG],
    Ziggs: [Role.MID, Role.ADC],
    Zilean: [Role.SUP],
    Zoe: [Role.MID],
    Zyra: [Role.MID, Role.SUP],
};

export const CHAMPION_EFFECTS: { [key: string]: (a: Event) => number } = {
    Aatrox: (a) => 1,
    Ahri: (a) => 1,
    Akali: (a) => 1,
    Akshan: (a) => 1,
    Alistar: (a) => 1,
    Amumu: (a) => 1,
    Anivia: (a) => 1,
    Annie: (a) => 1,
    Aphelios: (a) => 1,
    Ashe: (a) => 1,
    'Aurelion Sol': (a) => 1,
    Azir: (a) => 1,
    Bard: (a) => 1,
    Blitzcrank: (a) => 1,
    Brand: (a) => 1,
    Braum: (a) => 1,
    Caitlyn: (a) => 1,
    Camille: (a) => 1,
    Cassiopeia: (a) => 1,
    'Cho\'Gath': (a) => 1,
    Corki: (a) => 1,
    Darius: (a) => 1,
    Diana: (a) => 1,
    Mundo: (a) => 1,
    Draven: (a) => 1,
    Ekko: (a) => 1,
    Elise: (a) => 1,
    Evelynn: (a) => 1,
    Ezreal: (a) => 1,
    Fiddlesticks: (a) => 1,
    Fiora: (a) => 1,
    Fizz: (a) => 1,
    Galio: (a) => 1,
    Gangplank: (a) => 1,
    Garen: (a) => 1,
    Gnar: (a) => 1,
    Gragas: (a) => 1,
    Graves: (a) => 1,
    Gwen: (a) => 1,
    Hecarim: (a) => 1,
    Heimerdinger: (a) => 1,
    Illaoi: (a) => 1,
    Irelia: (a) => 1,
    Ivern: (a) => 1,
    Janna: (a) => 1,
    'Jarvan IV': (a) => 1,
    Jax: (a) => 1,
    Jayce: (a) => 1,
    Jhin: (a) => 1,
    Jinx: (a) => 1,
    'Kai\'sa': (a) => 1,
    Kalista: (a) => 1,
    Karma: (a) => 1,
    Karthus: (a) => 1,
    Kassadin: (a) => 1,
    Katarina: (a) => 1,
    Kayle: (a) => 1,
    Kayn: (a) => 1,
    Kennen: (a) => 1,
    'Kha\'Zix': (a) => 1,
    Kindred: (a) => 1,
    Kled: (a) => 1,
    'Kog\'Maw': (a) => 1,
    LeBlanc: (a) => 1,
    'Lee Sin': (a) => 1,
    Leona: (a) => 1,
    Lillia: (a) => 1,
    Lissandra: (a) => 1,
    Lucian: (a) => 1,
    Lulu: (a) => 1,
    Lux: (a) => 1,
    Malphite: (a) => 1,
    Malzahar: (a) => 1,
    Maoki: (a) => 1,
    'Master Yi': (a) => 1,
    'Miss Fortune': (a) => 1,
    Mordekaiser: (a) => 1,
    Morgana: (a) => 1,
    Nami: (a) => 1,
    Nasus: (a) => 1,
    Nautilus: (a) => 1,
    Neeko: (a) => 1,
    Nidalee: (a) => 1,
    Nocturne: (a) => 1,
    Nunu: (a) => 1,
    Olaf: (a) => 1,
    Orianna: (a) => 1,
    Ornn: (a) => 1,
    Pantheon: (a) => 1,
    Poppy: (a) => 1,
    Pyke: (a) => 1,
    Qiyana: (a) => 1,
    Quinn: (a) => 1,
    Rakan: (a) => 1,
    Rammus: (a) => 1,
    'Rek\'Sai': (a) => 1,
    Rell: (a) => 1,
    Renekton: (a) => 1,
    Rengar: (a) => 1,
    Riven: (a) => 1,
    Rumble: (a) => 1,
    Ryze: (a) => 1,
    Samira: (a) => 1,
    Sejuani: (a) => 1,
    Senna: (a) => 1,
    Seraphine: (a) => 1,
    Sett: (a) => 1,
    Shaco: (a) => 1,
    Shen: (a) => 1,
    Shyvana:(a) => 1,
    Singed:(a) => 1,
    Sion: (a) => 1,
    Sivir: (a) => 1,
    Skarner: (a) => 1,
    Sona: (a) => 1,
    Soraka:(a) => 1,
    Swain: (a) => 1,
    Sylas: (a) => 1,
    Syndra:(a) => 1,
    'Tahm Kench': (a) => 1,
    Taliyah: (a) => 1,
    Talon: (a) => 1,
    Taric: (a) => 1,
    Teemo: (a) => 1,
    Thresh: (a) => 1,
    Tristana: (a) => 1,
    Trundle: (a) => 1,
    Tryndamere:(a) => 1,
    'Twisted Fate':(a) => 1,
    Twitch:(a) => 1,
    Udyr: (a) => 1,
    Urgot: (a) => 1,
    Varus: (a) => 1,
    Vayne: (a) => 1,
    Veigar: (a) => 1,
    'Vel\'Koz':(a) => 1,
    Vex:(a) => 1,
    Vi: (a) => 1,
    Viego: (a) => 1,
    Viktor:(a) => 1,
    Vladimir: (a) => 1,
    Volibear:(a) => 1,
    Warwick: (a) => 1,
    Wukong: (a) => 1,
    Xayah: (a) => 1,
    Xerath:(a) => 1,
    'Xin Zhao': (a) => 1,
    Yasuo:(a) => 1,
    Yone: (a) => 1,
    Yorick: (a) => 1,
    Yuumi:(a) => 1,
    Zac:(a) => 1,
    Zed:(a) => 1,
    Ziggs: (a) => 1,
    Zilean:(a) => 1,
    Zoe: (a) => 1,
    Zyra: (a) => 1,
};

export const championNormalizationMap: any = Object.keys(CHAMPIONS)
    .reduce((accumulator, key) => {
        const normalizedName = normalizeChampionName(key);
        return { ...accumulator, [normalizedName]: key }
    }, {});