import { Role } from "./classes";
import { normalizeChampionName } from "../utils/normalization";

export interface ChampionData {
    name: string,
    roles: Role[]
}

export const CHAMPIONS: { [key: string]: Role[] } = {
    Aatrox: [Role.TOP],
    Ahri: [Role.MID],
    Akali: [Role.MID, Role.TOP],
    Akshan: [Role.MID, Role.ADC],
    Alistar: [Role.SUP],
    Amumu: [Role.JNG, Role.SUP],
    Anivia: [Role.MID, Role.ADC],
    Annie: [Role.MID],
    Aphelios: [Role.ADC],
    Ashe: [Role.ADC, Role.SUP],
    'Aurelion Sol': [Role.MID],
    Azir: [Role.MID],
    Bard: [Role.SUP],
    Blitzcrank: [Role.SUP],
    Brand: [Role.MID, Role.SUP],
    Braum: [Role.SUP],
    Caitlyn: [Role.ADC],
    Camille: [Role.TOP],
    Cassiopeia: [Role.MID, Role.ADC, Role.TOP],
    'Cho\'Gath': [Role.TOP, Role.JNG],
    Corki: [Role.MID],
    Darius: [Role.TOP, Role.JNG],
    Diana: [Role.MID, Role.JNG],
    Mundo: [Role.TOP, Role.JNG],
    Draven: [Role.ADC],
    Ekko: [Role.MID, Role.JNG],
    Elise: [Role.JNG],
    Evelynn: [Role.JNG],
    Ezreal: [Role.MID, Role.ADC],
    Fiddlesticks: [Role.JNG],
    Fiora: [Role.TOP],
    Fizz: [Role.MID],
    Galio: [Role.MID, Role.SUP],
    Gangplank: [Role.TOP],
    Garen: [Role.TOP, Role.MID, Role.JNG],
    Gnar: [Role.TOP],
    Gragas: [Role.TOP],
    Graves: [Role.JNG, Role.MID],
    Gwen: [Role.TOP, Role.JNG],
    Hecarim: [Role.JNG],
    Heimerdinger: [Role.MID],
    Illaoi: [Role.TOP],
    Irelia: [Role.TOP, Role.MID, Role.ADC],
    Ivern: [Role.JNG],
    Janna: [Role.SUP],
    'Jarvan IV': [Role.JNG],
    Jax: [Role.TOP, Role.JNG],
    Jayce: [Role.TOP, Role.MID],
    Jhin: [Role.ADC],
    Jinx: [Role.ADC],
    'Kai\'sa': [Role.ADC],
    Kalista: [Role.ADC],
    Karma: [Role.TOP, Role.SUP],
    Karthus: [Role.JNG],
    Kassadin: [Role.MID],
    Katarina: [Role.MID],
    Kayle: [Role.TOP],
    Kayn: [Role.JNG],
    Kennen: [Role.TOP],
    'Kha\'Zix': [Role.JNG],
    Kindred: [Role.JNG],
    Kled: [Role.TOP],
    'Kog\'Maw': [Role.ADC],
    LeBlanc: [Role.MID],
    'Lee Sin': [Role.JNG],
    Leona: [Role.SUP],
    Lillia: [Role.JNG, Role.TOP],
    Lissandra: [Role.MID],
    Lucian: [Role.ADC, Role.MID, Role.TOP],
    Lulu: [Role.SUP],
    Lux: [Role.MID, Role.SUP],
    Malphite: [Role.TOP, Role.MID, Role.JNG, Role.SUP],
    Malzahar: [Role.MID],
    Maoki: [Role.TOP, Role.SUP],
    'Master Yi': [Role.JNG],
    'Miss Fortune': [Role.ADC, Role.SUP],
    Mordekaiser: [Role.TOP, Role.JNG],
    Morgana: [Role.MID, Role.JNG, Role.SUP],
    Nami: [Role.SUP],
    Nasus: [Role.TOP, Role.JNG],
    Nautilus: [Role.SUP],
    Neeko: [Role.MID, Role.TOP],
    Nidalee: [Role.JNG],
    Nocturne: [Role.JNG, Role.MID],
    Nunu: [Role.JNG],
    Olaf: [Role.JNG],
    Orianna: [Role.MID],
    Ornn: [Role.TOP],
    Pantheon: [Role.TOP, Role.MID, Role.JNG, Role.SUP],
    Poppy: [Role.TOP, Role.JNG],
    Pyke: [Role.MID, Role.SUP],
    Qiyana: [Role.MID, Role.JNG],
    Quinn: [Role.TOP],
    Rakan: [Role.SUP],
    Rammus: [Role.JNG],
    'Rek\'Sai': [Role.JNG],
    Rell: [Role.SUP],
    Renekton: [Role.TOP],
    Rengar: [Role.TOP, Role.JNG],
    Riven: [Role.TOP],
    Rumble: [Role.TOP],
    Ryze: [Role.TOP, Role.MID],
    Samira: [Role.ADC],
    Sejuani: [Role.JNG],
    Senna: [Role.ADC, Role.SUP],
    Seraphine: [Role.MID, Role.ADC, Role.SUP],
    Sett: [Role.TOP, Role.SUP],
    Shaco: [Role.JNG],
    Shen: [Role.TOP],
    Shyvana: [Role.JNG],
    Singed: [Role.TOP],
    Sion: [Role.TOP, Role.JNG],
    Sivir: [Role.ADC],
    Skarner: [Role.JNG],
    Sona: [Role.SUP],
    Soraka: [Role.SUP],
    Swain: [Role.ADC, Role.SUP],
    Sylas: [Role.TOP, Role.MID, Role.JNG],
    Syndra: [Role.MID],
    'Tahm Kench': [Role.TOP, Role.SUP],
    Taliyah: [Role.MID, Role.JNG],
    Talon: [Role.MID, Role.JNG],
    Taric: [Role.SUP],
    Teemo: [Role.TOP, Role.SUP],
    Thresh: [Role.SUP],
    Tristana: [Role.MID, Role.ADC],
    Trundle: [Role.TOP, Role.JNG],
    Tryndamere: [Role.TOP],
    'Twisted Fate': [Role.MID],
    Twitch: [Role.ADC],
    Udyr: [Role.JNG],
    Urgot: [Role.TOP],
    Varus: [Role.ADC],
    Vayne: [Role.TOP, Role.ADC],
    Veigar: [Role.MID],
    'Vel\'Koz': [Role.MID, Role.SUP],
    Vex: [Role.MID],
    Vi: [Role.JNG, Role.MID],
    Viego: [Role.TOP, Role.MID, Role.JNG],
    Viktor: [Role.MID],
    Vladimir: [Role.MID, Role.TOP],
    Volibear: [Role.TOP, Role.JNG],
    Warwick: [Role.JNG],
    Wukong: [Role.TOP, Role.JNG],
    Xayah: [Role.ADC],
    Xerath: [Role.MID, Role.SUP],
    'Xin Zhao': [Role.JNG],
    Yasuo: [Role.TOP, Role.MID, Role.ADC],
    Yone: [Role.TOP, Role.MID],
    Yorick: [Role.TOP],
    Yuumi: [Role.SUP],
    Zac: [Role.JNG],
    Zed: [Role.MID, Role.JNG],
    Ziggs: [Role.MID, Role.ADC],
    Zilean: [Role.SUP],
    Zoe: [Role.MID],
    Zyra: [Role.MID, Role.SUP],
};

const championNormalizationMap: any = Object.keys(CHAMPIONS)
    .reduce((accumulator, key) => {
        const normalizedName = normalizeChampionName(key);
        return { ...accumulator, [normalizedName]: key }
    }, {});

export function getChampDataFromUserInput(name: string): ChampionData | null {
    const properName = championNormalizationMap[name];
    if (!properName) {
        return null;
    }
    return { name: properName, roles: CHAMPIONS[properName] };
}
